### ISSUE TITLE
Issue with multi-word package names in create-app command

### ISSUE THREAD

**Issue by sdelamo** [macprzepiora/web-vaadin8#3]
If you supply a multi-word package to Grails `create-app` command:

`test $ grails create-app com.demo --profile me.przepiora.vaadin-grails:web-vaadin8:0.2 --inplace`

There is an issue:

```
$ ./gradlew bootRun
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
:compileJava NO-SOURCE
:compileGroovy
startup failed:
/Users/sdelamo/Downloads/vaadin-tests/package-multiple-words/grails-app/vaadin/com/Com.demoGrailsUI.groovy: 14: unexpected token: . @ line 14, column 17.
   public class Com.demoGrailsUI extends UI{
                   ^

1 error

:compileGroovy FAILED

FAILURE: Build failed with an exception.

``` 

Grails Version 3.2.11

**Comment by macprzepiora** [comment]
It uses @grails.codegen.projectClassName@ variable in the skeleton, I am not aware of any other that would be better suited here. Do you have any idea?

**Comment by aaloise** [comment]
Tried with Grails 3.3.0 using version 0.4 web-vaadin8 and this is the output:

```
Warning! Gradle wrapper doesn't fully work. Please regenerate it with the following command:

gradle wrapper --gradle-version 4.0

Also please note that you need to edit build.gradle. Move line that reads 'apply plugin:"com.devsoap.plugin.vaadin" to the top of apply plugin block
```

No compilation errors but the class name became Com.demoGrailsUI instead of DemoGrailsUI

**Comment by aaloise** [comment]
I noticed that the same thing happens when one tries to create a project using the web-plugin profile. The class gets the whole project name.

I raised an issue at grails-core. Maybe there's something not well with @grails.codegen.projectClassName@

https://github.com/grails/grails-core/issues/10764

**Comment by macprzepiora** [comment]
I believe it is Grails issue. Therefore closing.
